# Generated by Django 3.2.5 on 2021-07-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='link',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(default='Draft Post', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Post under work. Please check back sometime later.'),
        ),
    ]
